version: '3'
services:
  leitner-calendar:
    container_name: leitner_calendar
    build: .
    image: leitner-calendar

# Uses external network with routing
networks:
  default:
    external:
      name: production