version: '3'
services:
  leitner-calendar:
    container_name: leitner_calendar
    build:
      context: .
      args:
        - NODE_ENV=production
    image: leitner-calendar

# Uses external network with routing
networks:
  default:
    external:
      name: production